apiVersion: v1
kind: Pod
metadata:
  name: good-security
  namespace: supply-chain
spec:
  containers:
    - name: test
      image: reg.kyverno.io/kyverno/kyverno@sha256:b31d8511ae5fd6010e2a01ea72ebae08eb82fa51d91af14a1d9fe989949b4edb
      securityContext:
        privileged: false
        runAsNonRoot: true
        runAsUser: 10001
