apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: supply-chain
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: secure-software-supply-chain
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
