apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: supply-chain
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: secure-software-supply-chain
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
