apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: backend-image
    newName: 542489916995.dkr.ecr.eu-west-3.amazonaws.com/secure-software-supply-chain-dev-backend
    digest: sha256:5552cf0ecc5a4e06dd4405af0457d1ff15b76c600d7468dabacc2658ae4e666e

  - name: frontend-image
    newName: 542489916995.dkr.ecr.eu-west-3.amazonaws.com/secure-software-supply-chain-dev-frontend
    digest: sha256:41882c97a420e06c0210fc6b04a4dda3af065df9cffcca1f73697c535d5db37f

labels:
  - pairs:
      environment: dev
